---
title: "Data Science HW #6"
author: "Nathalie Fadel"
date: "11/19/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(purrr)
library(modelr)
```

#Problem 1  

##Data import and cleaning
```{r}
murder_data = read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")

murder_data = murder_data %>%
  unite("city_state", c("city", "state"), sep = ",", remove = TRUE)

murder_data = murder_data %>%
  mutate(solved_case = ifelse(disposition == c("Closed by arrest"), 1, 0)) %>%
  mutate(victim_race = ifelse(victim_race != "White", "Non-White", "White")) %>%
  mutate(victim_race = forcats::fct_relevel(victim_race, "White", "Non-White")) %>%
  mutate(victim_age = as.numeric(victim_age)) %>%
  mutate(victim_sex = forcats::fct_relevel(victim_sex, "Male", "Female", "Unknown"))

murder_data = murder_data %>%
  filter(!(city_state %in% c("Dallas,TX,", "Phoenix,AZ", "Kansas City,MO", "Tulsa,AL")))  
```

##Logistic Regression
```{r}
baltimore_df = murder_data %>%
  filter(city_state %in% c("Baltimore,MD")) %>%
  select(solved_case, victim_age, victim_race, victim_sex)
  
baltimore_logistic = 
  baltimore_df %>% 
  glm(solved_case ~ victim_age + victim_race + victim_sex, data = ., family = binomial()) 

broom::tidy(baltimore_logistic) %>%
  mutate(OR = exp(estimate), 
         UB = exp(estimate+1.96 * std.error), 
         LB = exp(estimate-1.96 * std.error)) %>%
  filter(term == "victim_raceNon-White") %>%
  select(OR, LB, UB) %>% 
  knitr::kable(digits = 3)

city_logistic =
  murder_data %>%
  group_by(city_state) %>%
  nest()

 city_logistic =
   city_logistic %>%
   mutate(solved_logit = map(data, ~glm(solved_case ~ victim_race +  victim_sex + victim_age, data = .x, family = binomial)),
    solved_logit = map(solved_logit, broom::tidy)) %>%
  select(-data) %>%
  unnest()
 
  filter(term == "victim_raceNon-White") %>%
  mutate(OR = exp(estimate), 
         UB = exp(estimate+1.96 * std.error), 
         LB = exp(estimate-1.96 * std.error)) %>%
  select(city_state, OR, LB, UB) %>% 
  knitr::kable(digits = 3)
  
```
